function Invoke-NativeCommand {
    <#
        .SYNOPSIS
        Executes a native command and fails the run when it returns a non-zero exit code.
    #>
    [Alias('Exec', 'Run')]
    [CmdletBinding()]
    param(
        # The command and its arguments.
        [Parameter(ValueFromRemainingArguments)]
        [string[]] $Command
    )
    $cmd = $Command[0]
    $arguments = $Command[1..$Command.Length]
    $fullCommand = "$cmd $($arguments -join ' ')"
    Write-Verbose "Executing: $fullCommand"
    $output = & $cmd @arguments
    if ($LASTEXITCODE -ne 0) {
        Write-Error "Command failed with exit code $LASTEXITCODE`: $fullCommand" -ErrorId 'NativeCommandFailed' -Category OperationStopped
    }
    if ($output -is [array] -and $output.Count -gt 1) {
        return $output -join "`n"
    }
    return $output
}

$repoName = $env:GITHUB_REPOSITORY
$repoRoot = Split-Path -Path $PSScriptRoot -Parent
$srcRoot = Join-Path -Path $repoRoot -ChildPath 'src'

Connect-GitHubApp -Organization 'PSModule' -Default
$repo = Get-GitHubRepository -Owner 'PSModule' -Name 'Lovdata'

LogGroup 'Checkout' {
    $script:currentBranch = (Run git rev-parse --abbrev-ref HEAD).Trim()
    $script:defaultBranch = $repo.DefaultBranch

    Write-Output "Current branch: $currentBranch"
    Write-Output "Default branch: $defaultBranch"
    Run git fetch origin
    Run git checkout $defaultBranch
    Run git pull origin $defaultBranch

    $script:timeStamp = Get-Date -Format 'yyyyMMdd-HHmmss'
    if ($currentBranch -eq $defaultBranch) {
        $script:targetBranch = "auto-update-$timeStamp"
        Write-Output "Running on default branch. Creating new branch: $targetBranch"
        Run git checkout -b $targetBranch
    } else {
        $script:targetBranch = $currentBranch
        Write-Output "Running on feature branch. Using existing branch: $targetBranch"
        Run git checkout $targetBranch
        Run git merge origin/$defaultBranch
    }
}

LogGroup 'Load module source' {
    # Reuse the module's own classes and parser by dot-sourcing the source in framework order, so the
    # index is regenerated by the exact code the module ships rather than a reimplementation.
    $order = 'classes\private', 'classes\public', 'functions\private', 'functions\public',
    'variables\private', 'variables\public'
    foreach ($part in $order) {
        $dir = Join-Path -Path $srcRoot -ChildPath $part
        if (-not (Test-Path -LiteralPath $dir)) {
            continue
        }
        Get-ChildItem -Path $dir -Recurse -Filter '*.ps1' | Sort-Object -Property FullName | ForEach-Object {
            . $_.FullName
        }
    }
    Write-Output 'Loaded the Lovdata classes and parsers from src.'
}

LogGroup 'Regenerate index' {
    $work = Join-Path -Path ([System.IO.Path]::GetTempPath()) -ChildPath "lovdata-$timeStamp"
    $null = New-Item -Path $work -ItemType Directory -Force

    $packages = Get-LovdataPublicDataset -FileName 'gjeldende-*'
    $script:packageInfo = @(
        foreach ($package in $packages) {
            Write-Output "Downloading [$($package.FileName)] ($([math]::Round($package.SizeBytes / 1MB, 1)) MB)"
            $file = Save-LovdataPublicDataset -FileName $package.FileName -Path $work -Force
            $null = Expand-LovdataPublicDataset -Path $file.FullName -Force
            [pscustomobject]@{
                FileName     = $package.FileName
                LastModified = $package.LastModified.ToString('o')
            }
        }
    )

    $documents = Get-ChildItem -Path $work -Recurse -Filter '*.xml' | ForEach-Object {
        Get-LovdataDocument -Path $_.FullName
    }
    Write-Output "Parsed $($documents.Count) documents."
    $null = $documents | Export-LovdataIndex -Path $srcRoot
    Remove-Item -Path $work -Recurse -Force -ErrorAction SilentlyContinue
}

$changes = Run git status --porcelain -- 'src/LovdataIndex.*.json'
if ([string]::IsNullOrWhiteSpace($changes)) {
    Write-Output 'No updates available.'
    Write-GitHubNotice 'No updates available.'
    return
}

LogGroup 'Summarise changes' {
    # Compare the committed index against the freshly generated one and report per-document counts
    # rather than the raw multi-megabyte diff.
    $readIndex = {
        param($text)
        $map = [ordered]@{}
        if (-not [string]::IsNullOrWhiteSpace($text)) {
            foreach ($doc in ($text | ConvertFrom-Json).documents) {
                $map[$doc.RefID] = ($doc | ConvertTo-Json -Depth 20 -Compress)
            }
        }
        $map
    }

    $added = 0
    $removed = 0
    $changed = 0
    foreach ($file in Get-ChildItem -Path $srcRoot -Filter 'LovdataIndex.*.json') {
        if ($file.Name -eq 'LovdataIndex.manifest.json') {
            continue
        }
        $relative = "src/$($file.Name)"
        $oldText = Run git show "HEAD:$relative"
        if ($LASTEXITCODE -ne 0) {
            $oldText = ''
        }
        $old = & $readIndex $oldText
        $new = & $readIndex ([System.IO.File]::ReadAllText($file.FullName))
        foreach ($refId in $new.Keys) {
            if (-not $old.Contains($refId)) {
                $added++
            } elseif ($old[$refId] -ne $new[$refId]) {
                $changed++
            }
        }
        foreach ($refId in $old.Keys) {
            if (-not $new.Contains($refId)) {
                $removed++
            }
        }
    }

    $manifest = [ordered]@{
        schemaVersion = 1
        builtAt       = (Get-Date).ToUniversalTime().ToString('o')
        packages      = @($packageInfo)
    }
    $manifestJson = ($manifest | ConvertTo-Json -Depth 5) -replace "`r`n", "`n"
    $manifestPath = Join-Path -Path $srcRoot -ChildPath 'LovdataIndex.manifest.json'
    [System.IO.File]::WriteAllText($manifestPath, "$manifestJson`n", [System.Text.UTF8Encoding]::new($false))

    $script:summaryBody = @"
## Lovdata index updated

| Change | Documents |
| --- | --- |
| Added | $added |
| Changed | $changed |
| Removed | $removed |

Built from packages: $(($packageInfo.FileName) -join ', ').
"@
    Write-Output $summaryBody
    Set-GitHubStepSummary $summaryBody
}

LogGroup 'Commit and open PR' {
    Run git add src/LovdataIndex.manifest.json
    Get-ChildItem -Path $srcRoot -Filter 'LovdataIndex.*.json' | ForEach-Object {
        Run git add "src/$($_.Name)"
    }
    Run git commit -m 'Update the Lovdata metadata index'

    if ($targetBranch -eq $currentBranch -and $currentBranch -ne $defaultBranch) {
        Run git push origin $targetBranch
        Write-Output "Changes committed and pushed to existing branch: $targetBranch"
        return
    }

    Run git push --set-upstream origin $targetBranch
    Run gh pr create --base $defaultBranch --head $targetBranch --title "Update Lovdata index $timeStamp" --body $summaryBody

    # Supersede any older open auto-update PRs so only the newest stays open.
    $newPR = $null
    $retry = 0
    while ($null -eq $newPR -and $retry -lt 3) {
        if ($retry -gt 0) {
            Start-Sleep -Seconds $retry
        }
        $listed = Run gh pr list --repo $repoName --head $targetBranch --state open --json 'number,title' --limit 1
        $newPR = $listed | ConvertFrom-Json | Select-Object -First 1
        $retry++
    }
    if ($null -eq $newPR -or $null -eq $newPR.number) {
        Write-Warning 'Could not retrieve the newly created PR. Skipping supersedence.'
        return
    }

    $existingJson = Run gh pr list --repo $repoName --state open --json 'number,title,headRefName'
    $existing = $existingJson | ConvertFrom-Json |
        Where-Object { $_.number -ne $newPR.number -and $_.headRefName -like 'auto-update-*' }
    foreach ($pr in $existing) {
        Write-Output "Closing superseded PR #$($pr.number): $($pr.title)"
        $comment = "This PR has been superseded by #$($newPR.number) and will be closed automatically."
        Run gh pr comment $pr.number --repo $repoName --body $comment
        Run gh pr close $pr.number --repo $repoName
        if ($pr.headRefName) {
            $null = Run gh api -X DELETE "repos/$repoName/git/refs/heads/$($pr.headRefName)"
        }
    }
}
